In [20]:
import numpy as np


In [21]:
movies = np.array(["Padayappa", "Adhi", "Goat", "Youth", "Karuppu", "Viswanath&Sons"])
ratings = np.array([
    [5, 1, 5, 0, 0, 0],
    [4, 2, 5, 5, 0, 0],
    [0, 5, 1, 4, 5, 0],
    [5, 0, 4, 5, 4, 0],
    [0, 5, 2, 4, 5, 0]
])

print(ratings)

[[5 1 5 0 0 0]
 [4 2 5 5 0 0]
 [0 5 1 4 5 0]
 [5 0 4 5 4 0]
 [0 5 2 4 5 0]]


In [22]:
user_id = int(input("Enter User ID (1-5): "))
user_index = user_id - 1
user_ratings = ratings[user_index]
print("\nSelected User:", user_id)
print("Ratings:", user_ratings)

Enter User ID (1-5): 2

Selected User: 2
Ratings: [4 2 5 5 0 0]


In [23]:
similarity = np.zeros(len(ratings))

for i in range(len(ratings)):

    if i == user_index:
        similarity[i] = -1
        continue
    similarity[i] = np.dot(user_ratings, ratings[i]) / (
        np.linalg.norm(user_ratings) * np.linalg.norm(ratings[i])
    )
print("Similarity:", similarity)

Similarity: [ 0.78661776 -1.          0.51107145  0.85794098  0.57142857]


In [24]:
similar_users = np.argsort(similarity)[::-1]
print("Similar Users:", similar_users + 1)

Similar Users: [4 1 5 3 2]


In [25]:
unwatched = np.where(user_ratings == 0)[0]
print("Unwatched Movies:")

for movie in unwatched:
    print(movies[movie])

Unwatched Movies:
Karuppu
Viswanath&Sons


In [26]:
recommendation_scores = np.zeros(len(movies))

for user in similar_users:

    if user == user_index:
        continue

    for movie in unwatched:

        if ratings[user, movie] > 0:
            recommendation_scores[movie] += (
                similarity[user] * ratings[user, movie]
            )

print("Recommendation Scores:", recommendation_scores)

Recommendation Scores: [0.         0.         0.         0.         8.84426402 0.        ]


In [27]:
sorted_movies = np.argsort(recommendation_scores)[::-1]

recommendations = []

for movie in sorted_movies:

    if movie in unwatched:
        recommendations.append(movie)

    if len(recommendations) == 3:
        break

print("\nTop 3 Recommended Movies:")

for i, movie in enumerate(recommendations, start=1):
    print(i, ".", movies[movie])


Top 3 Recommended Movies:
1 . Karuppu
2 . Viswanath&Sons
